In [2]:
import pandas as pd 
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.preprocessing import scale

In [3]:
wd=pd.read_csv(r'C:\Users\Narasimha\yashdata\iris (1).csv')

In [4]:
wd.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [5]:
wd.isnull().sum()

Sepal.Length    0
Sepal.Width     0
Petal.Length    0
Petal.Width     0
Species         0
dtype: int64

In [6]:
wd.iloc[:,0:4].astype(int).head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
0             5            3             1            0
1             4            3             1            0
2             4            3             1            0
3             4            3             1            0
4             5            3             1            0

In [7]:

x=wd.loc[:,['Sepal.Length','Sepal.Width','Petal.Length','Petal.Width']]
y=wd.loc[:,'Species']


In [8]:
X=scale(x)

In [9]:
X

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

In [10]:
X=pd.DataFrame(X)

In [11]:
X

0         1         2         3
0   -0.900681  1.019004 -1.340227 -1.315444
1   -1.143017 -0.131979 -1.340227 -1.315444
2   -1.385353  0.328414 -1.397064 -1.315444
3   -1.506521  0.098217 -1.283389 -1.315444
4   -1.021849  1.249201 -1.340227 -1.315444
5   -0.537178  1.939791 -1.169714 -1.052180
6   -1.506521  0.788808 -1.340227 -1.183812
7   -1.021849  0.788808 -1.283389 -1.315444
8   -1.748856 -0.362176 -1.340227 -1.315444
9   -1.143017  0.098217 -1.283389 -1.447076
10  -0.537178  1.479398 -1.283389 -1.315444
11  -1.264185  0.788808 -1.226552 -1.315444
12  -1.264185 -0.131979 -1.340227 -1.447076
13  -1.870024 -0.131979 -1.510739 -1.447076
14  -0.052506  2.169988 -1.453901 -1.315444
15  -0.173674  3.090775 -1.283389 -1.052180
16  -0.537178  1.939791 -1.397064 -1.052180
17  -0.900681  1.019004 -1.340227 -1.183812
18  -0.173674  1.709595 -1.169714 -1.183812
19  -0.900681  1.709595 -1.283389 -1.183812
20  -0.537178  0.788808 -1.169714 -1.315444
21  -0.900681  1.479398 -1.283389 -1.052180
22  -1.506521  1.249201 -1.567576 -1.315444
23  -0.900681  0.558611 -1.169714 -0.920548
24  -1.264185  0.788808 -1.056039 -1.315444
25  -1.021849 -0.131979 -1.226552 -1.315444
26  -1.021849  0.788808 -1.226552 -1.052180
27  -0.779513  1.019004 -1.283389 -1.315444
28  -0.779513  0.788808 -1.340227 -1.315444
29  -1.385353  0.328414 -1.226552 -1.315444
..        ...       ...       ...       ...
120  1.280340  0.328414  1.103783  1.448832
121 -0.294842 -0.592373  0.649083  1.053935
122  2.249683 -0.592373  1.672157  1.053935
123  0.553333 -0.822570  0.649083  0.790671
124  1.038005  0.558611  1.103783  1.185567
125  1.643844  0.328414  1.274295  0.790671
126  0.432165 -0.592373  0.592246  0.790671
127  0.310998 -0.131979  0.649083  0.790671
128  0.674501 -0.592373  1.046945  1.185567
129  1.643844 -0.131979  1.160620  0.527406
130  1.886180 -0.592373  1.331133  0.922303
131  2.492019  1.709595  1.501645  1.053935
132  0.674501 -0.592373  1.046945  1.317199
133  0.553333 -0.592373  0.762758  0.395774
134  0.310998 -1.052767  1.046945  0.264142
135  2.249683 -0.131979  1.331133  1.448832
136  0.553333  0.788808  1.046945  1.580464
137  0.674501  0.098217  0.990108  0.790671
138  0.189830 -0.131979  0.592246  0.790671
139  1.280340  0.098217  0.933271  1.185567
140  1.038005  0.098217  1.046945  1.580464
141  1.280340  0.098217  0.762758  1.448832
142 -0.052506 -0.822570  0.762758  0.922303
143  1.159173  0.328414  1.217458  1.448832
144  1.038005  0.558611  1.103783  1.712096
145  1.038005 -0.131979  0.819596  1.448832
146  0.553333 -1.282963  0.705921  0.922303
147  0.795669 -0.131979  0.819596  1.053935
148  0.432165  0.788808  0.933271  1.448832
149  0.068662 -0.131979  0.762758  0.790671

[150 rows x 4 columns]

In [12]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [13]:
y_test.head()

14         setosa
98     versicolor
75     versicolor
16         setosa
131     virginica
Name: Species, dtype: object

In [14]:
knn = KNeighborsClassifier(n_neighbors = 10, metric='euclidean')

knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                     weights='uniform')

In [15]:
knn

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                     weights='uniform')

In [16]:
y_pred=knn.predict(x_test)

In [ ]:
from sklearn.preprocessing import Label_Bibarizse

In [22]:
np.Binaraize(y_pred)

AttributeError: module 'numpy' has no attribute 'Binaraize'

In [19]:
prob=knn.predict_proba(x_test)
prob

array([[1. , 0. , 0. ],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [1. , 0. , 0. ],
       [0. , 0.1, 0.9],
       [0. , 0.6, 0.4],
       [0. , 0. , 1. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0. , 0. , 1. ],
       [0. , 1. , 0. ],
       [1. , 0. , 0. ],
       [0. , 0. , 1. ],
       [0. , 0.8, 0.2],
       [0. , 0.7, 0.3],
       [1. , 0. , 0. ],
       [0. , 1. , 0. ],
       [0. , 0.8, 0.2],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0. , 1. , 0. ],
       [0. , 0.8, 0.2],
       [0. , 0.6, 0.4],
       [1. , 0. , 0. ],
       [0. , 0.2, 0.8],
       [0. , 1. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0. , 0.9, 0.1],
       [0. , 0.2, 0.8]])

In [36]:
np.mean(y_pred==y_test)

1.0

In [38]:
confusion_matrix(y_pred,y_test)

array([[11,  0,  0],
       [ 0, 13,  0],
       [ 0,  0,  6]], dtype=int64)

In [39]:
from sklearn.datasets import load_wine

In [40]:
wine=load_wine()

In [41]:
wine

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

In [43]:
x=pd.DataFrame(wine)

ValueError: arrays must all be same length

In [44]:
print(wine.feature_names)

['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']


In [45]:
print(wine.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [48]:
a=wine.data


In [49]:
b=wine.target

In [53]:
from sklearn.neighbors import KNeighborsClassifier


In [54]:
knn=KNeighborsClassifier(n_neighbors=10)

In [56]:
knn.fit(x,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                     weights='uniform')

In [57]:
knn.fit(x_train,y_train)
ypred=knn.predict(x_test)


ValueError: Classification metrics can't handle a mix of continuous-multioutput and multiclass targets

In [25]:
import numpy as np
>>> from sklearn import metrics
>>> y = np.array([1, 1, 2, 2])
>>> scores = np.array([0.1, 0.4, 0.35, 0.8])
>>> fpr, tpr, thresholds = metrics.roc_curve(y, scores, pos_label=2)
>>> fpr


array([0. , 0. , 0.5, 0.5, 1. ])

In [26]:
tpr

array([0. , 0.5, 0.5, 1. , 1. ])

In [27]:
thresholds

array([1.8 , 0.8 , 0.4 , 0.35, 0.1 ])